TicketShop/TicketShop/Controllers/MvcApp/EventController.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using TicketShop.Services.ModelsDto;
using TicketShop.Services.Services.Interfaces;
using TicketShop.Web.Extensions;
using TicketShop.Web.ViewModels;

namespace TicketShop.Web.Controllers.MvcApp
{
    public class EventController : Controller
    {
        private readonly IEventService _eventService;

        public EventController(IEventService eventService)
        {
            _eventService = eventService;
        }

        [HttpGet]
        [AllowAnonymous]
        public IActionResult Events()
        {
            List<EventDto> foundedEventsDto = _eventService.GetActualDateEvents().ToList();
            List<EventWeb> eventsWeb = foundedEventsDto.EventDtoToEventWeb(foundedEventsDto);

            return View(eventsWeb);
        }

        [HttpGet]
        [AllowAnonymous]
        public IActionResult ExtendedFindEvents()
        {
            List<EventDto> foundedEventsDto = _eventService.GetActualDateEvents().ToList();
            List<EventWeb> eventsWeb = foundedEventsDto.EventDtoToEventWeb(foundedEventsDto);

            return View(eventsWeb);
        }
    }
}

TicketShop/TicketShop/Controllers/MvcApp/HomeController.cs
using System;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;

namespace TicketShop.Web.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult SetLanguage(string culture, string returnUrl)
        {
            Response.Cookies.Append(
                CookieRequestCultureProvider.DefaultCookieName,
                CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
                new CookieOptions { Expires = DateTimeOffset.UtcNow.AddYears(1) }
            );

            return LocalRedirect(returnUrl);
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Asp.Net Core project";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Contact page.";

            return View();
        }
    }
}

TicketShop/TicketShop/Controllers/MvcApp/OrderController.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using TicketShop.Services.ModelsDto;
using TicketShop.Services.Services.Interfaces;
using TicketShop.Web.Extensions;
using TicketShop.Web.ViewModels;

namespace TicketShop.Web.Controllers
{
    public class OrderController : Controller
    {
        private readonly IOrdersService _ordersService;
        private readonly IUserService _userService;
        private readonly ITicketService _ticketService;

        public OrderController(IOrdersService ordersService, IUserService userService, ITicketService ticketService)
        {
            _ordersService = ordersService;
            _userService = userService;
            _ticketService = ticketService;
        }

        [HttpGet]
        [Authorize("Admin, User")]
        public IActionResult AddToOrder(int ticketId)
        {
            int buyerId =
                _userService.GetUsers().FirstOrDefault(name => name.Email == HttpContext.User.Identity.Name).Id;
            _ordersService.AddToOrder(buyerId, ticketId);

            return View();
        }

        [HttpGet]
        [Authorize("Admin, User")]
        public IActionResult MyOrders()
        {
            List<TicketDto> tickets = _ticketService.GetTickets().ToList();

            List<OrderDto> foundedOrdersDto = _ordersService.GetOrdersByUserName(User.Identity.Name).ToList();
            List<MyOrdersWeb> myOrdersWebs = foundedOrdersDto.OrderDtoToMyOrderWeb(foundedOrdersDto, tickets);

            return View(myOrdersWebs);
        }
    }
}

TicketShop/TicketShop/Views/Home/About.cshtml
@using Microsoft.AspNetCore.Mvc.Localization

@inject IViewLocalizer Localizer

@{
    Layout = "~/Views/Shared/_Master.cshtml";
}

@{
    ViewData["Title"] = @Localizer["About"].Value;
}
<div class="container" style="margin-top: 130px">
    <h2>@ViewData["Title"].</h2>
    <h3>@ViewData["Message"]</h3>
</div>
<script src="~/lib/jquery/dist/jquery.min.js"></script>

TicketShop/TicketShop/Views/Home/Contact.cshtml
@using Microsoft.AspNetCore.Mvc.Localization

@inject IViewLocalizer Localizer

@{
    Layout = "~/Views/Shared/_Master.cshtml";
}

@{
    ViewData["Title"] = @Localizer["ContactPage"].Value;
}

<div class="container" style="margin-top: 130px">
    <h2>@ViewData["Title"].</h2>
    <p></p>
    
    <address>
        <abbr title="Phone">@Localizer["Phone"].Value</abbr>
        +375(44) 750-29-99
        <br />
        <abbr title="skype">@Localizer["Skype"].Value</abbr>
        TheShadowOfGod
        <br />
        <strong>@Localizer["Support"].Value</strong> <a href="mailto:Joisoc0@gmail.com">Joisoc0@gmail.com</a><br />
    </address>
</div>

<script src="~/lib/jquery/dist/jquery.min.js"></script>

TicketShop/TicketShop/Views/Home/Index.cshtml
@using Microsoft.AspNetCore.Mvc.Localization

@inject IViewLocalizer Localizer

@{
    Layout = "~/Views/Shared/_Master.cshtml";
}

<div>
    <span id="hours"></span>
</div>

<script type="text/javascript">

    obj_hours = document.getElementById("hours");

    name_month = new Array(
        "января",
        "февраля",
        "марта",
        "апреля",
        "мая",
        "июня",
        "июля",
        "августа",
        "сентября",
        "октября",
        "ноября",
        "декабря");
    name_day = new Array(
        "воскресенье",
        "понедельник",
        "вторник",
        "среда",
        "четверг",
        "пятница",
        "суббота");

    function wr_hours() {
        time = new Date();

        time_sec = time.getSeconds();
        time_min = time.getMinutes();
        time_hours = time.getHours();
        time_wr = ((time_hours < 10) ? "0" : "") + time_hours;
        time_wr += ":";
        time_wr += ((time_min < 10) ? "0" : "") + time_min;

        time_wr = name_day[time.getDay()] +
            ", " +
            time.getDate() +
            " " +
            name_month[time.getMonth()] +
            " " +
            time.getFullYear() +
            " " +
            time_wr;

        obj_hours.innerHTML = time_wr;
    }

    wr_hours();
    setInterval("wr_hours();", 1000);

</script>


@{
    if (@User != null && @User.Identity.IsAuthenticated)
    {
        <div style="margin-top: 150px">
            <h3>
                <a asp-controller="Event" asp-action="Events">@Localizer["Events"].Value</a>
                <hr>

                <a asp-controller="Ticket" asp-action="MyTicketsSelling">@Localizer["MyTickets"].Value</a>
                <hr>

                <a asp-controller="Order" asp-action="MyOrders">@Localizer["MyOrders"].Value</a>
                <hr>

                <a asp-controller="Account" asp-action="UserInfo">@Localizer["UserInfo"].Value</a>
                <hr>
            </h3>
        </div>
    }
    else
    {
        <div class="container" style="margin-top: 130px">
            <h2>
                <b>@Localizer["WarningAuthorizastion"].Value</b>
            </h2>
            <hr/>
            <h2>
                <a asp-controller="Event" asp-action="Events">@Localizer["Events"].Value</a>
            </h2>
        </div>
    }
}

<script src="~/lib/jquery/dist/jquery.min.js"></script>